config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  resources :reviews
  resources :favorites
  resources :internships do 
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
    resources :comments, except: [:index, :show] do
      resources :comments, except: [:index, :show]
    end
    resources :favorites, only: [:new, :create, :destroy]
  end
  devise_for :users

  # To fix the error that occured when user sign out
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users, only: [:show]
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :favorite_user, class_name: "User"
  belongs_to :favorite_internship, class_name: "Internship"
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: [:show, :edit, :update]
  before_action :authenticate_user!

  # GET /favorites
  # GET /favorites.json
  def index
    @favorites = current_user.favorites.order(created_at: :desc)
  end

  # GET /favorites/1
  # GET /favorites/1.json
  def show
  end

  # GET /favorites/new
  def new
    @favorite = Favorite.new
  end

  # GET /favorites/1/edit
  def edit
  end

  # POST /favorites
  # POST /favorites.json
  def create
    @favorite = Favorite.new(favorite_internship_id: params[:internship_id], favorite_user_id: current_user.id)

    respond_to do |format|
      if @favorite.save
        format.html { redirect_back fallback_location: root_path, notice: 'Le stage a été ajouté à vos favoris.' }
        format.json { render :show, status: :created, location: @favorite }
      else
        format.html { redirect_back fallback_location: root_path, notice: "Le favori n'a pas pu être créé : #{@favorite.errors.messages}" }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favorites/1
  # PATCH/PUT /favorites/1.json
  def update
    respond_to do |format|
      if @favorite.update(favorite_params)
        format.html { redirect_to @favorite, notice: 'Favorite was successfully updated.' }
        format.json { render :show, status: :ok, location: @favorite }
      else
        format.html { render :edit }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1
  # DELETE /favorites/1.json
  def destroy
    if params[:internship_id]
      Favorite.find_by(favorite_user_id: current_user.id, favorite_internship_id: params[:id]).destroy
    else
      Favorite.find(params[:id]).destroy
    end

    respond_to do |format|
      format.html { redirect_back fallback_location: root_path, notice: 'Le stage a été retiré de vos favoris.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite
      @favorite = Favorite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favorite_params
      params.require(:favorite).permit(:favorite_user_id, :favorite_internship_id)
    end

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_form.html.erb
 <%= form_tag internship_favorites_path(@internship), method:"post" do %>

  <%= hidden_field_tag(:favorite_user_id, current_user.id) %>
  <%= hidden_field_tag(:favorite_internship_id, @internship.id) %>

<% end %>

app/views/favorites/edit.html.erb
<h1>Editing Favorite</h1>

<%= render 'form', favorite: @favorite %>

<%= link_to 'Show', @favorite %> |
<%= link_to 'Back', favorites_path %>

app/views/favorites/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container container-show mb-5">
  <h1 class="mb-5">Mes favoris</h1>
  <div class="text-dark">
    <% if @favorites == [] || @favorites == nil %>
      <p>Vous n'avez pas de stages en favoris.</p>
    <% else %>
      <div class="container">
        <div class="row">
          <% @favorites.each do |favorite| %>
            <div class="col-lg-4 col-md-6 col-sm-12">
              <div class="card m-3">
                <div class="card-header">
                  <div class="row">
                    <div class="col-10 text-dark">
                      <%= favorite.favorite_internship.title %>
                    </div>
                    <div class="col-2">
                      <%= link_to 'X', favorite, method: :delete, data: { confirm: 'Êtes-vous sûr de vouloir retirer ce stage de vos favoris ?' }, class: "btn btn-danger btn-sm" %>
                    </div>
                  </div>
                </div>
                <div class="card-body">
                  <h6 class="card-subtitle mb-2 text-muted"><%= favorite.favorite_internship.city %></h6>
                  <p class="text-muted">Spécialité : <%= favorite.favorite_internship.specialty %></p>
                  <p class="text-muted">Niveau : <%= favorite.favorite_internship.cursus %></p>
                  <p class="text-muted">Population : <%= favorite.favorite_internship.population %></p>
                  <%= link_to "Voir le stage", internship_path(favorite.favorite_internship.id), class: "btn btn-secondary" %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to "Retour", :back, class: "btn btn-outline-secondary mt-3" %>
</div>

app/views/favorites/new.html.erb
<h1>New Favorite</h1>

<%= render 'form', favorite: @favorite %>

<%= link_to 'Back', favorites_path %>

app/views/favorites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @favorite.favorite_user %>
</p>

<p>
  <strong>Internship:</strong>
  <%= @favorite.favorite_internship %>
</p>

<%= link_to 'Edit', edit_favorite_path(@favorite) %> |
<%= link_to 'Back', favorites_path %>