config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  resources :reviews
  resources :favorites
  resources :internships do 
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
    resources :comments, except: [:index, :show] do
      resources :comments, except: [:index, :show]
    end
    resources :favorites, only: [:new, :create, :destroy]
  end
  devise_for :users

  # To fix the error that occured when user sign out
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users, only: [:show]
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content,
    presence: true,
    length: { maximum: 750 }
  belongs_to :questioner, class_name: "User"
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy

  def parent_internship
  	if self.commentable_type == "Internship"
  	  return Internship.find(self.commentable_id)
  	else   
  	  return Internship.find(Comment.find(self.commentable_id).commentable_id)
  	end
  end

  def parent_comment
    if self.commentable_type == "Comment"
      return Comment.find(self.commentable_id)
    end
  end

  def has_unread_answers
    if self.comments != nil || self.comments != []
      if self.comments.where(read: false).length != 0
        return true
      else
        return false
      end
    else
      return false
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_commentable
  before_action :set_comment, only: [:edit, :update, :destroy]
  before_action :current_user_must_own_comment, only: [:edit, :update, :destroy]

  # GET /comments/new
  def new
    @comment = @commentable.comments.build
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @commentable.comments.build(comment_params)
    @comment.questioner = current_user
    if params[:comment_id] && params[:internship_id]
      @comment.commentable_type = "Comment"
    else
      @comment.commentable_type = "Internship"
    end

    respond_to do |format|
      if @comment.save
        if params[:comment_id] && params[:internship_id]
          format.html { redirect_to internship_path(@commented_internship), notice: 'Le commentaire a été posté.' }
          format.json { render :show, status: :created, location: @comment }
        else 
          format.html { redirect_to internship_path(@commentable), notice: 'Le commentaire a été posté.' }
          format.json { render :show, status: :created, location: @comment }    
        end
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        if params[:comment_id] && params[:internship_id]
          format.html { redirect_to internship_path(@commented_internship), notice: 'Le commentaire a été modifié.' }
          format.json { render :show, status: :ok, location: @comment }
        else
          format.html { redirect_to internship_path(@commentable), notice: 'Le commentaire a été modifié.' }
          format.json { render :show, status: :ok, location: @comment }
        end
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      if params[:comment_id] && params[:internship_id]
        format.html { redirect_to internship_path(@commented_internship), notice: 'Le commentaire a été supprimé.' }
        format.json { head :no_content }
      else
        format.html { redirect_to internship_path(@commentable), notice: 'Le commentaire a été supprimé.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = @commentable.comments.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :questioner_id, :commentable_id)
    end

    # Editing permission only for owner
    def current_user_must_own_comment
      if current_user.id != @comment.questioner.id
        if params[:comment_id] && params[:internship_id]
          redirect_to internship_path(@commented_internship)
        else
          redirect_to internship_path(@commentable)
        end 
      end
    end

    def get_commentable
      if params[:comment_id]
        @commentable = Comment.find(params[:comment_id])
        @commented_internship = Internship.find(params[:internship_id])
      else
        @commentable = Internship.find(params[:internship_id])
      end
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="container ml-5">
  <div class="media mb-3">
    <div class="media-body">
      <h5 class="media-heading"><%= link_to comment.questioner.first_name + " " + comment.questioner.last_name, user_path(comment.questioner), class: "review-user" %></h5>
      <span class="media-heading"><%= comment.created_at.strftime("%d/%m/%Y") %></span>
  <!-- EDIT BUTTON -->
      <% if current_user == comment.questioner %>

        <%= button_to [@internship, comment.parent_comment, comment], method: :delete, data: { confirm: "Êtes-vous sûr ?" }, class:"btn btn-sm mt-2 edit-button" do %> <i class="fas fa-times-circle fa-3x text-danger" title="Supprimer le commentaire"></i>
        <% end %>


        <button class="btn btn-outline-primary btn-sm my-4 edit-button">
        <i class="fa fa-edit"></i>
        <%= link_to 'Modifier', edit_internship_comment_comment_path(@internship, comment.commentable_id, comment) %> </button>
      <% end %>
      <p class="bg-light-blue p-4 rounded"> <%= comment.content %></p>
    </div>
  </div>  
</div>

app/views/comments/_form.html.erb
<% if @new_internship_comment %>
  <%= form_with(model: [@internship, comment], local: true) do |form| %>
    <% if comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(comment.errors.count, "error") %> a/ont empêché ce commentaire d'être posté:</h2>
        <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <h6 class="text-primary">Une question ? Pose la dans les commentaires</h6>

    <div class="form-group mb-6">
      <%= form.text_area :content, class: "form-control", placeholder: "Ecrivez votre commentaire" %>
    </div>

    <div class="actions form-group">
      <%= form.submit "Poster le commentaire", class: "btn btn-primary text-uppercase" %>
    </div>
  <% end %>
<% else %>
  <%= form_with(model: [@commented_internship, @commentable, comment], local: true) do |form| %>
    <% if comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(comment.errors.count, "error") %> a/ont empêché ce commentaire d'être posté:</h2>
        <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 form-group mb-6">
          <%= form.text_area :content, class: "form-control", placeholder: "Votre réponse" %>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4 actions form-group">
          <%= form.submit "Envoyer la réponse", class: "btn btn-primary text-uppercase" %>
        </div>
      </div>
  </div>

  <% end %>
<% end %>

app/views/comments/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<h1>Modifier le commentaire</h1>
		</div>
	</div>
</div>
<%= render 'form', comment: @comment %>

<div class="mt-3 mb-5 ml-3">
	<%= link_to 'Retour', internship_path(params[:internship_id]), class:"btn btn-outline-secondary mt-3"%>
</div>

app/views/comments/new.html.erb
<div class="container">
  <h1>Répondre au commentaire :</h1>
  <div class="media mb-3">
    <div class="media-body">
      <h5 class="media-heading"><%= @commentable.questioner.first_name %> <%= @commentable.questioner.last_name %></h5>
      <h6 class="media-heading"><%= @commentable.created_at %></h6>
      <p class="bg-light p-4 rounded"> <%= @commentable.content %></p>
      <hr>
    </div>
  </div>
  <%= render 'form', comment: @comment %>
  <%= link_to 'Retour', internship_path(@commented_internship) %>
</div>