config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  resources :reviews
  resources :favorites
  resources :internships do 
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
    resources :comments, except: [:index, :show] do
      resources :comments, except: [:index, :show]
    end
    resources :favorites, only: [:new, :create, :destroy]
  end
  devise_for :users

  # To fix the error that occured when user sign out
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users, only: [:show]
end

app/models/user.rb
class User < ApplicationRecord
  require 'dotenv'
  Dotenv.load

  before_save :add_to_mailchimp_list

  validates :email,
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/ }
  validates :first_name,
    presence: true,
    length: { in: 2..20 }
  validates :last_name,
    presence: true,
    length: { in: 2..25 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :internships

  has_many :comments, foreign_key: "questioner_id", dependent: :destroy
  has_many :commentables, foreign_key: "commentable_id", through: :comments

  has_many :reviews, foreign_key: "review_user_id"
  has_many :review_internships, foreign_key: 'review_internship_id', class_name: "Internship", through: :reviews

  has_many :favorites, foreign_key: "favorite_user_id"
  has_many :favorite_internships, foreign_key: "favorite_internship_id", class_name: "Internship", through: :favorites

  after_create :welcome_send

  def unread_internships_comments
    unread_comments = []
    unless self.internships == nil || self.internships == []
      self.internships.each do |internship|
        internship.comments.where(read: false).each do |comment|
          unread_comments << comment
        end
      end
    end
    return unread_comments
  end

  def unread_comments_answers
    unread_answers = []
    unless self.comments == nil || self.comments == []
      self.comments.each do |comment|
        comment.comments.where(read: false).each do |answer|
          unread_answers << answer
        end
      end
    end
    return unread_answers
  end

  def add_to_mailchimp_list
    list_id = ENV["MAILCHIMP_LIST_ID"]
    gibbon = Gibbon::Request.new(api_key: ENV["MAILCHIMP_API_KEY"])
    subscribe = gibbon.lists(list_id).members(Digest::MD5.hexdigest(self.email)).upsert(body: { email_address: self.email, status: "subscribed", merge_fields: {FNAME: self.first_name, LNAME: self.last_name}})
  end

  def unread_comments
    total_unread_comments = unread_internships_comments + unread_comments_answers
    return total_unread_comments
  end

  def internships_with_unread_comments
    total_internships_with_unread_comments = []
    self.unread_comments.each do |unread_comment|
      if unread_comment.commentable_type == "Internship"
        total_internships_with_unread_comments << unread_comment.commentable_id
      else
        total_internships_with_unread_comments << Comment.find(unread_comment.commentable_id).commentable_id
      end
    end
    return total_internships_with_unread_comments
  end

  def notifications_number
    self.internships_with_unread_comments.uniq.length
  end

  def uniq_comments
    internships = []
    self.comments.each do |comment|
      if comment.commentable_type == "Internship"
        internships << Internship.find(comment.commentable_id).title
      else
        internships << Internship.find(Comment.find(comment.commentable_id).commentable_id).title
      end
    end
    return internships.uniq
  end

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  # GET /users/1
  # GET /users/1.json
  def show
    @internships = @user.internships
    @comments = @user.comments.sort_by{ |comment| comment.has_unread_answers ? 0 : 1 }.paginate(page: params[:page], per_page: 4)
    @reviews = @user.reviews
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div class="text-white">

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_registration_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_registration_path %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<section class="mb-2">
  <div class="container container-show">
      <!-- ====================================
——— INFO USER
===================================== -->
    <div class="row mb-3">
    	<div class="col-lg-6 mb-3">
        <div class="card">
        	<% if current_user.id == @user.id %>
            <h5 class="card-header text-dark">Mes informations</h5>
        	<% else %>
        	  <h5 class="card-header text-dark">Informations</h5>
        	<% end %>
          <div class="card-body">
            <p>Prénom : <%= @user.first_name %></p>
            <p>Nom : <%= @user.last_name %></p>
            <% if current_user.id == @user.id %>
              <p>Email : <%= @user.email %></p>
              <%= link_to 'Modifer les informations', edit_user_registration_path(@user), class: "btn btn-primary mt-3" %>
            <% end %>
          </div>
        </div>
    	</div>
        <!-- ====================================
——— INTERNSHIPS USER
===================================== -->
    	<div class="col-lg-6">
        <div class="card">
        	<% if current_user.id == @user.id %>
            <h5 class="card-header text-dark">Mes expériences de stage</h5>
        	<% else %>
        	  <h5 class="card-header text-dark">Expériences de stage</h5>
        	<% end %>
          <div class="card-body">
            <% if current_user.id == @user.id && (@user.internships == [] || @user.internships == nil) %>
              <p>Vous n'avez pas encore renseigné de stage. Pensez à le faire pour aider la communauté !</p>
            <% elsif current_user.id != @user.id && (@user.internships == [] || @user.internships == nil) %>
            	<p>Cet utilisateur n'a pas renseigné d'expérience de stage.</p>
            <% else %>
              <% @internships.each do |internship| %>
                <div class="row">
                	<div class="col-6">
                    <% if internship.has_unread_comments && current_user == @user %>
                      <i class="fas fa-bell mr-3 text-danger"></i>
                    <% end %>
                    <span><%= link_to internship.title, internship_path(internship.id) %></span>
                	</div>
    	            <div class="col-6 text-right">
    	              <% if current_user.id == @user.id %>
                      <div class="row justify-content-end">
      	                <%= link_to "Modifier", edit_internship_path(internship.id), class: "btn btn-primary" %>
                        <%= button_to internship_path(internship.id),  method: :delete, data: { confirm: "Êtes-vous sûr ?" }, class:"btn btn-sm" do %>
                          <i class="fas fa-times-circle fa-3x text-danger" title="Supprimer l'expérience"></i>
                        <% end %>
                      </div>
                    <% end %>
    	            </div>   
                </div>
    	          <hr>
              <% end %>
            <% end %>
            <%= link_to "Ajouter une expérience de stage", new_internship_path, class: "btn btn-success mt-2" %>
          </div>
        </div>	
    	</div>
    </div>
      <!-- ====================================
——— COMMENTS USER
===================================== -->
    <div class="row">
    	<div class="col-lg-6 mb-3">
        <div class="card">
        	<% if current_user.id == @user.id %>
            <h5 class="card-header text-dark">Mes stages commentés</h5>
        	<% else %>
        	  <h5 class="card-header text-dark">Stages commentés</h5>
        	<% end %>
          <div class="card-body">
            <% if current_user.id == @user.id && (@comments == [] || @comments == nil) %>
              <p>Vous n'avez pas encore écrit de commentaire.</p>
            <% elsif current_user.id != @user.id && (@comments == [] || @comments == nil) %>
            	<p>Cet utilisateur n'a pas encore fait de commentaires.</p>
            <% else %>
    	        <% @comments.each do |comment| %>
    	          <div class="row">
    	            <div class="col-6">
                    <% if comment.has_unread_answers %>
                      <i class="fas fa-bell mr-3 text-danger"></i>
                    <% end %>
                    <span><%= link_to comment.parent_internship.title, internship_path(comment.parent_internship) %></span>
    	            </div>
    	            <div class="col-6">
    	              <span><%= comment.content[0..50] %></span>
                    <% if comment.content.length > 50 %>
                      <span>...</span>
                    <% end %>
    	            </div>
    	          </div>
                  <% unless comment == @comments.last %>
                    <hr>
                  <% end %>
    	        <% end %>          
            <% end %>
            <!-- PAGINATION COMMENTS-->
            <div class="pagination mt-3 pr-5">
              <a><%= will_paginate @comments %></a>
            </div>
          </div>
        </div>
    	</div>
        <!-- ====================================
——— FAVORITES USER
===================================== -->
    	<div class="col-lg-6">
    	  <% if current_user.id == @user.id %>
          <div class="card">
            <h5 class="card-header text-dark">Mes stages favoris</h5>
            <div class="card-body">
              <% if @user.favorites == [] || @user.favorites == nil %>
                <p>Vous n'avez pas encore de stage en favori.</p>
              <% else %>
    	          <% @user.favorites.each do |favorite| %>
    	            <div class="row">
    	              <div class="col-6">
    	              	<span><%= link_to favorite.favorite_internship.title, internship_path(favorite.favorite_internship.id) %></span>
    	              </div>
    	              <div class="col-6 text-right">
    	              	<%= link_to "Retirer", favorite_path(favorite.id), data: { confirm: "Êtes-vous sûr ?" }, method: :delete, class: "btn btn-danger" %>
    	              </div>
    	            </div>
                  <% unless favorite == @user.favorites.last %>
                	  <hr>
                  <% end %>
    	          <% end %>
              <% end %>
            </div>
          </div>
        <% end %>
    	</div>
    </div>


  <!-- ====================================
——— REVIEWS
===================================== -->
  <div class="pb-8 pt-5 table-review height100vh">
    <div class="container">
      <% if current_user.id == @user.id %>
        <h2 class="font-weight-normal mb-4 mb-md-0">Mes avis</h2><br>
      <% else %>
        <h2 class="font-weight-normal mb-4 mb-md-0">Avis</h2><br>
      <% end %>
      <% if @user.reviews == nil || @user.reviews == [] %>
        <hr>
        <p>Vous n'avez pas encore écrit d'avis</p>
      <% else %>
        <table id="my-reviews-lg" class="display nowrap table-data-default" style="width:100%">
          <thead class="text-dark">
            <tr>
              <th class="text-capitalize py-2">Titre</th>
              <th class="text-capitalize py-2">Expérience</th>
              <th class="text-capitalize py-2">Note</th>
              <th class="text-capitalize py-2">Message</th>
              <th class="text-capitalize py-2"></th>
            </tr>
          </thead>
          <% @reviews.each do |review| %>
            <tbody class="bg-secondary">
              <tr>
                <td class="text-capitalize td-title py-3">
                  <span class="text-muted font-weight-bold"><%= review.title %></span>
                </td>
                <td>
                  <span class="font-weight-bold"><%= review.review_internship.title %></span>
                </td>
                <td class="td-no-white-space">
                  <ul class="list-inline list-inline-rating">
                    <% review.notation.to_i.times do %>
                    <li class="list-inline-item">
                      <i class="fa fa-star" aria-hidden="true"></i>
                    </li>
                    <% end %>
                    <% (5 - review.notation).to_i.times do %>
                    <li class="list-inline-item">
                      <i class="fa fa-star-o" aria-hidden="true"></i>
                    </li>
                    <% end %>
                  </ul>
                </td>
                <td class="td-details">
                  <%= review.description[0..30] %>...     
                </td>
                <td class="td-buttons-2">
                  <div class="d-flex flex-column flex-lg-row">
                    <% if current_user.id == @user.id %>
                      <%= link_to 'Voir', review, class: "btn btn-outline-primary btn-sm edit-button" %>
                      <button class="btn btn-outline-primary btn-sm ">
                        <i class="fa fa-edit"></i><%= link_to 'Editer', edit_review_path(review) %>
                      </button>
                      <%= button_to internship_review_path(review.review_internship_id, review), method: :delete, data: { confirm: "Êtes-vous sûr ?" }, class:"btn-like px-2" do %> 
                      <i class="fas fa-times-circle fa-2x text-danger" title="Supprimer l'avis"></i>
                      <% end %>
                      <% else %>
                      <%= link_to 'Voir', review, class: "btn btn-outline-primary btn-sm edit-button" %>
                      <% end %>
                    </div>
                  </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>


<!-- CARD RESPONSIVE REVIEW MOBILE VERSION -->
  <section class="container d-lg-none">
    <div class="card">
      <h5 class="card-header d-lg-noneader text-dark bg-light">Mes avis</h5>
      <div class="card-body bg-secondary">
        <% if @user.reviews == nil || @user.reviews == [] %>
          <p>Vous n'avez pas encore écrit d'avis</p>
        <% else %>
          <% @reviews.each do |review| %>
            <div class="row">
              <div class="col-4">
                <span><%= review.title %></span>
              </div>
              <div class="col-5 text-center">
                <ul class="list-inline list-inline-rating mr-4">
                  <% review.notation.to_i.times do %>
                  <li class="list-inline-item">
                    <i class="fa fa-star" aria-hidden="true"></i>
                  </li>
                  <% end %>
                  <% (5 - review.notation).to_i.times do %>
                  <li class="list-inline-item">
                    <i class="fa fa-star-o" aria-hidden="true"></i>
                  </li>
                  <% end %>
                </ul>
              </div>
              <div class="col-3 ">
                <% if current_user.id == @user.id %>
                    <%= link_to 'Voir', review, class: "btn btn-primary btn-sm mr-2 mb-2" %>
                    <button class="btn btn-outline-primary btn-sm mr-2 mb-2">
                      <%= link_to 'Editer', edit_review_path(review) %>
                    </button>
                    <%= button_to internship_review_path(review.review_internship_id, review), method: :delete, data: { confirm: "Êtes-vous sûr ?" }, class:"btn-like pr-5 mb-2" do %> 
                    <i class="fas fa-times-circle fa-2x text-danger" title="Supprimer l'avis"></i>
                  <% end %>
                  <% else %>
                    <%= link_to 'Voir', review, class: "btn btn-primary btn-sm" %>
                <% end %>
              </div>
            </div>
            <hr>
          <% end %>

        <% end %>
      </div>
    </div>
  </section>

 <div class="ml-6 mb-6">
    <%= link_to 'Retour', root_path, class: "btn btn-outline-secondary mt-3" %>
  </div>