config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  resources :reviews
  resources :favorites
  resources :internships do 
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
    resources :comments, except: [:index, :show] do
      resources :comments, except: [:index, :show]
    end
    resources :favorites, only: [:new, :create, :destroy]
  end
  devise_for :users

  # To fix the error that occured when user sign out
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users, only: [:show]
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all.order(created_at: :desc).paginate(page: params[:page], per_page: 5)
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
    current_user_must_own_review
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(title: params[:title], notation: params[:notation], description: params[:description], review_user_id: params[:review_user_id], review_internship_id: params[:review_internship_id])
    @review.review_user = current_user

    respond_to do |format|
      if @review.save
        format.html { redirect_back fallback_location: root_path, notice: "Votre avis a été posté." }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { redirect_back fallback_location: root_path, notice: "L'avis n'a pas pu être créé : #{@review.errors.messages}" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Votre avis a été modifié.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy

    respond_to do |format|
      format.html { redirect_back fallback_location: root_path, notice: "L'avis a été supprimé." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:title, :notation, :description, :review_internship, :review_user)
    end

    # Editing permission only for owner
    def current_user_must_own_review
      if current_user.id != @review.review_user_id
        redirect_to review_path(@review.id)
      end
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_edit_form.html.erb
<%= form_with(model: review, local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(internship.errors.count, "erreurs") %> ont empêché la sauvegarde de la modification:</h2>
      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<section>
  <div class="container container-form">
    <div class="card bg-secondary">
      <div class="card-body text-dark">
        <div class="card-header text-uppercase text-dark style-card "> Lieu de stage</div>
        <hr>
        <div>
          <p> * <i>Tous les champs sont obligatoires</i></p>
        </div>
        <div class="row">
          <div class="form-group col-sm-6 col-xs-12">
            <%= form.label :title, class:"font-weight-bold" %>
            <%= form.text_field :title, class:"form-control bg-transparent border-form" %>
            </div>
            <div class="form-group col-sm-6 col-xs-12">
              <%= form.label :note, class:"font-weight-bold" %>
              <%= form.number_field :notation, min: 1, max: 5, class:"form-control bg-transparent border-form" %>
              </div>
          </div>
            <div class="form-group col-xs-12">
              <%= form.label :description, class:"font-weight-bold" %>
              <%= form.text_area :description, class:"form-control bg-transparent border-form" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

      <div class="row justify-content-center">
        <div class="col-sm-6 col-xs-12">
          <div class="mb-4">
            <button type="submit" class="btn btn-lg btn-primary btn-block">Envoyer</button>
          </div>
        </div>
      </div>
    <% end %>
</section>

app/views/reviews/_form.html.erb
<div class="text-center">
  <div>
    <p> * <i>Tous les champs sont obligatoires</i></p>
  </div>

  <%= form_tag internship_reviews_path(@internship), method:"post" do %>
    <div class="form-group">
      <p class="font-weight-bold text-dark text-uppercase">Titre de l'avis</p>
      <p class="form control"><%= text_field_tag :title %></p>
    </div>

    <div class="form-group" >
      <p class="font-weight-bold text-dark text-uppercase">Note</p>
      <input id="notation" max="5.0" min="1.0" name="notation" type="number"/>
    </div>

    <div class="form-group">
      <p class="font-weight-bold text-dark text-uppercase">Description</p>
      <textarea name="description" id="description" rows="12" placeholder="Ecris ici tes impressions et ressentis sur cette expérience de stage..."></textarea>
    </div>
    
    <%= hidden_field_tag(:review_user_id, current_user.id) %>
    <%= hidden_field_tag(:review_internship_id, @internship.id) %>

    <div class="form-group actions">
      <%= submit_tag "Envoyer l'avis", class:"btn btn-primary text-uppercase" %>
    </div>
  <% end %>
</div> 

app/views/reviews/edit.html.erb
<section>
	<h1 class="text-center text-primary">Editer l'avis</h1>
	<%= render 'edit_form', review: @review %>
</section>

<section>
	<div class= "container">
		<%= link_to "Voir l'avis", @review, class: "btn btn-outline-dark mt-3" %>
		<%= link_to "Retour sur l'expérience", internship_path(@review.review_internship_id),  class: "btn btn-outline-dark mt-3" %>
	</div>
</section>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<!-- ====================================
——— REVIEWS
===================================== -->
<section class="pb-8 pt-5 height100vh">
  <div class="container">

    <!-- Breadcrumb -->
    <nav class="bg-transparent breadcrumb breadcrumb-2 px-0 mb-5" aria-label="breadcrumb">
      <h2 class="font-weight-normal mb-4 mb-md-0">Avis</h2>
    </nav>

    <table id="table-reviews" class="display nowrap table-data-default" style="width:100%">
      <thead>
        <tr>
          <th class="text-capitalize">Titre</th>
          <th>Crée par</th>
          <th>Posté le</th>
          <th class="text-capitalize">Note</th>
          <th class="text-capitalize">Contenu</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
         <% @reviews.each do |review| %>
        <tr>
          <td class="text-capitalize td-title">
            <p class="text-muted"><%= review.title %></p>
          </td>
          <td>
            <div class="media media-xs align-items-center">
              <div class="media-body">
                <p class="text-muted font-weight-bold"><%= review.review_user.first_name %> <%= review.review_user.last_name %></p>
              </div>
            </div>
          </td>
          <td>
            <span class="d-block"><%= review.created_at.strftime("%d / %m / %Y") %></span>
          </td>
          <td class="td-no-white-space">
            <ul class="list-inline list-inline-rating">
              <li class="list-inline-item">
                <i class="fa fa-star" aria-hidden="true"></i>
              </li>
              <li class="list-inline-item">
                <i class="fa fa-star" aria-hidden="true"></i>
              </li>
              <li class="list-inline-item">
                <i class="fa fa-star" aria-hidden="true"></i>
              </li>
              <li class="list-inline-item">
                <i class="fa fa-star" aria-hidden="true"></i>
              </li>
              <li class="list-inline-item">
                <i class="fa fa-star-o" aria-hidden="true"></i>
              </li>
              <span>(<%= review.notation %>)</span>
            </ul>
          </td>
          <td class="bg-success text-white d-block p-2 mt-3 rounded"><%= review.description[0..30] %>...
          </td>
          <td>
            <button class="btn btn-outline-primary btn-sm">
              <i class="fas fa-arrow-circle-right" aria-hidden="true"></i> <%= link_to 'Voir', review %>
            </button>
          </td>
        </tr>
      </tbody>
        <% end %>
    </table>
  </div>
</section>

<section>
  <!-- PAGINATION -->
  <div class="pagination">
    <a><%= will_paginate @reviews %></a>
  </div>
</section>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<section class="pb-8 pt-5 height100vh">
    <div class="container text-center">
      <h3 class="font-weight-normal mb-6 text-center text-capitalize"><%= @review.title %></h3><hr>
      <div class="media mb-3">
      	<div class="media-body">
      		<p>Posté le <%= @review.created_at.strftime("%d / %m / %Y") %>
          </p>
	      <h5 class="media-heading"><%= @review.review_user.first_name %> <%= @review.review_user.last_name%></h5>
	      <!-- STARS NOTATION REVIEW -->
	      <ul class="list-inline list-inline-rating">
          <% @review.notation.to_i.times do %>
	        <li class="list-inline-item">
	          <i class="fa fa-star" aria-hidden="true"></i>
	        </li>
          <% end %>
          <% (5 - @review.notation).to_i.times do %>
          <li class="list-inline-item">
            <i class="fa fa-star-o" aria-hidden="true"></i>
          </li>
          <% end %>
	      </ul>
	      <p class="bg-secondary p-4 rounded text-dark"> <%= @review.description %></p>
	    </div>
      </div>
</section>

<section class="pb-8 pt-5 height100vh">
  <div class="container">
      <h2 class="font-weight-normal mb-4 mb-md-0">A propos de cet avis</h2><br>

    <table id="table-reviews" class="display nowrap table-data-default" style="width:100%">
      <thead>
        <tr>
          <th class="text-capitalize">Concerne l'expérience</th>
          <th>Contenu</th>
          <th></th>
        </tr>
      </thead>

      <tbody class="bg-secondary">
        <tr>
          <td class="text-capitalize td-title">
            <p class="text-muted font-weight-bold"><%= @review.review_internship.title %></p>
          </td>
         
          <td class="text-dark"><%= @review.review_internship.description[0..30] %>...
          </td>
          <td>
              <%= link_to 'Voir', internship_path(@review.review_internship_id), class: "btn btn-outline-primary btn-sm"%>
            </td>
        </tr>
      </tbody>
    </table>
  </div>
  <br>
  <div class="container">
    <% if current_user.id == @review.review_user_id %>
    <%= link_to 'Retour', internship_path(@review.review_internship_id), class: "btn btn-outline-dark mt-3" %>
  	<%= link_to 'Editer', edit_review_path(@review), class: "btn btn-outline-dark mt-3" %>
    <% else %>
    <%= link_to 'Retour', reviews_path, class: "btn btn-outline-dark mt-3" %>
    <% end %>
  	</div>
</section>